name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
build: 
  run-on: ubuntu-latest
  steps:
  -name: Checkout Repo
   uses: action/checkout@v3
  -name: Run Feed Generator
   uses: Punksoul000/Podcast-generator@main
