







^X
nano .github/workflows/main.yml

   name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # Replace with your test command

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to production"  # Replace with your deploy command

nano

